server:
    port: 8080
    servlet:
        context-path: /todo-app

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todolist
        username: root
        password: coderslab
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp